# Generated by Django 5.1.3 on 2024-11-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
